#' Simulated sparse-event hypoglycemia data
#'
#' A **simulated** dataset that mimics the structure of a sparse
#' severe-hypoglycemia endpoint in a two-arm randomized trial. It is provided so
#' that the examples and vignette of \pkg{EmpiricalRate} can be run without
#' access to confidential trial data. It does **not** contain any real patient
#' data; in particular it is not the QWINT-5 data analysed in the companion
#' paper, which are confidential.
#'
#' The data were generated by `data-raw/make_hypo_sim.R`. Postbaseline counts
#' were drawn from a negative binomial distribution whose mean depends on the
#' arm, the exposure, and (multiplicatively) the baseline event rate, so that
#' the baseline covariates carry genuine but not log-linear prognostic
#' information.
#'
#' @format A data frame with 500 rows (250 per arm) and 5 variables:
#' \describe{
#'   \item{arm}{Factor with levels `"Control"` and `"Treatment"`.}
#'   \item{events}{Integer count of postbaseline events for the subject.}
#'   \item{exposure_years}{Follow-up time in years (strictly positive).}
#'   \item{baseline_hba1c}{Baseline HbA1c (in percent), a continuous covariate.}
#'   \item{baseline_rate}{Baseline event rate (events per year during a lead-in
#'     period); sparse and right-skewed, with many zeros.}
#' }
#'
#' @examples
#' data(hypo_sim)
#' str(hypo_sim)
#' # Observed aggregate rate by arm:
#' with(hypo_sim, tapply(events, arm, sum) / tapply(exposure_years, arm, sum))
"hypo_sim"
